### ISSUE TITLE
Support themes from mdThemingProvider

### ISSUE THREAD

**Issue by codebreach** [SimeonC/md-date-time#6]
We are using this component in a site powered by angular material and I was looking to enable mdTheming support so that it blends in with the rest of the site.

This should be as simple as updating the html to use `md-classnames`.
We could make this an option passed to the jade to allow use without angular material.
Was wondering if you would be open to this as a PR.

**Comment by SimeonC** [comment]
Sure, go for it. I haven't been able to really look into angular material, though it looks awesome, as my use has been in bootstrap so I have no real knowledge about the themeing included or time to figure it out at the moment.

Change as much or as little as you need, I don't really mind as long as it still works without the material stuff - I'm happy to check through this once you've done the PR.
If you're changing the class names to the `md-classnames` just make sure to update them in the stylus file as well. If necessary we can split that styles file out into a generic stylesheet for dimensions etc and a theme file to apply the colors outside of angular material theming.

**Comment by codebreach** [comment]
I quite like the idea of splitting up the style. That way, for non angular material users, I can update the instructions to include it, much like you have to include a shim for md-button.

Will send you a PR when ready!

**Comment by scanferla** [comment]
+1

**Comment by zeeshanjan82** [comment]
Any updates on this as I too need to use the control on my website and have it follow the theme using themeprovider.

**Comment by zeeshanjan82** [comment]
+1

**Comment by knvpk** [comment]
+1

**Comment by SimeonC** [comment]
I've done some work now with angular-material, and there's a big issue with trying to get into this stuff in nicely as pointed out here: https://github.com/angular/material/issues/1269 (<- this is one of the reasons we gave up on angular-material too...)

Until that issue is solved I think the best way is to generate your own stylesheets from the stylus (less and sass version would look 90% the same - I may upload a sass option at some point) as we don't know what the "Official" solution will be sadly.

**Comment by SimeonC** [comment]
Moving to new repo https://github.com/SimeonC/sc-date-time/issues/1
